server {
    listen 80 default_server;
    server_name _;

    location /oht3d/ {
        alias /home/ubuntu/opensource_st_4/amhs/oht_3d/;
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://127.0.0.1:8501;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
    }
}
