apiVersion: v1
kind: Service
metadata:
  name: amhs-gat-streamlit
  namespace: amhs-mlops
spec:
  selector:
    app: amhs-gat-streamlit
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  type: ClusterIP
